#  Module Name: 
#  database setup file 

#  Created By: Farid faridaiman@schinkels.com.my 
#  Created: 18/6/2022 
#  Framework: Rails 7.0.3 on dangabay
#  Last Edited: 22/6/2022
#  Reason Edited: clean up code

# Set default value for all environment
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

# Development environment setup
development:
  <<: *default
  database: dangabay
  host: rds-dangabay-mysql80.crlozpzigni5.ap-southeast-1.rds.amazonaws.com
  username: asif_schinkels
  password: asifpwd@1234
#  database: dbapp_development
#  host: localhost
#  username: root
#  password: farid

# Test environment setup
test:
  <<: *default
  database: 
  username: 
  password: 

# Production environment setup
production:
  <<: *default
  database: 
  username: 
  password: 
